<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>tectonica</RootNamespace>
    <AssemblyName>tectonica</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcCoreMgd">
      <HintPath>C:\Autodesk\ObjectARX2025\inc\AcCoreMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDbMgd">
      <HintPath>C:\Autodesk\ObjectARX2025\inc\AcDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>C:\Autodesk\ObjectARX2025\inc\AcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDx">
      <HintPath>C:\Autodesk\ObjectARX2025\inc\AcDx.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
